import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const bitter = localFont({
  src: "./fonts/Bitter.ttf",
  variable: "--font-bitter",
  weight: "100 900",
});
const bitterItalics = localFont({
  src: "./fonts/Bitter-Italics.ttf",
  variable: "--font-bitter-italics",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bitter.variable} ${bitterItalics.variable} antialiased font-bitter`}
      >
        {children}
      </body>
    </html>
  );
}
